theme: jekyll-theme-slate
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

#Jekyll Configuration
name: W. Tyler McCleery
description: personal website of W. Tyler McCleery, displaying research, interests, code samples, and resume
url: "https://wtmccleery.github.io"
markdown: GFM
